language: node_js
node_js:
  - '12.8.0'
cache:
  directories:
    - node_modules
  yarn: true
script:
  - yarn lint
  - yarn test
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    branch: master
